Repository E2NEXT/spms, pull requests merged in 2024-04, with the labels that each got.

#55 Feat/reports
  spms/hooks.py
  spms/public/js/item.js
  spms/public/js/payment_entry.js
  spms/sales_person_management_system/custom/payment_entry.json
  spms/sales_person_management_system/doctype/collecting/collecting.js
  spms/sales_person_management_system/doctype/collecting/collecting.json
  spms/sales_person_management_system/doctype/collecting/collecting.py
  spms/sales_person_management_system/doctype/collects_goal/collects_goal.json
  spms/sales_person_management_system/doctype/commission/__init__.py
  spms/sales_person_management_system/doctype/commission/commission.json
  spms/sales_person_management_system/doctype/commission/commission.py
  spms/sales_person_management_system/doctype/reference_invoice_collects/reference_invoice_collects.json
  spms/sales_person_management_system/doctype/visit_goal/visit_goal.py
  spms/sales_person_management_system/doctype/visiting/visiting.json
  spms/sales_person_management_system/notification/__init__.py
  spms/sales_person_management_system/notification/test/__init__.py
  spms/sales_person_management_system/notification/test/test.json
  spms/sales_person_management_system/notification/test/test.md
  spms/sales_person_management_system/notification/test/test.py
  spms/sales_person_management_system/report/salesperson_wise_detailed/__init__.py
  spms/sales_person_management_system/report/salesperson_wise_detailed/salesperson_wise_detailed.js
  spms/sales_person_management_system/report/salesperson_wise_detailed/salesperson_wise_detailed.json
  spms/sales_person_management_system/report/salesperson_wise_detailed/salesperson_wise_detailed.py
  spms/sales_person_management_system/report/salesperson_wise_targets/__init__.py
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.js
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.json
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.py
Labels: size/XXL

#56 add previews account balance
  spms/sales_person_management_system/doctype/collecting/collecting.js
  spms/sales_person_management_system/doctype/collecting/collecting.json
  spms/sales_person_management_system/doctype/visiting/visiting.json
  spms/sales_person_management_system/report/fund_balance/__init__.py
  spms/sales_person_management_system/report/fund_balance/fund_balance.js
  spms/sales_person_management_system/report/fund_balance/fund_balance.json
  spms/sales_person_management_system/report/fund_balance/fund_balance.py
Labels: size/L

#57 work on barcode
  spms/methods/utils.py
  spms/public/js/item.js
  spms/sales_person_management_system/custom/item_barcode.json
  spms/sales_person_management_system/print_format/barcode_35mm_x_15mm/__init__.py
  spms/sales_person_management_system/print_format/barcode_35mm_x_15mm/barcode_35mm_x_15mm.json
Labels: size/L

#58 fund balance total row removal
  spms/sales_person_management_system/report/fund_balance/fund_balance.py
Labels: size/XS
