Repository E2NEXT/spms, pull requests merged in 2024-05, with the labels that each got.

#59 Cpa report
  spms/sales_person_management_system/report/customer_payment_analysis/__init__.py
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.js
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.json
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.py
Labels: size/L

#60 report fixes
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.js
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.py
Labels: size/L

#61 report fixes v2
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.js
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.py
Labels: size/S

#62 report fixes v3
  spms/sales_person_management_system/report/customer_payment_analysis/customer_payment_analysis.py
Labels: size/S

#64 report v2 fix #1
  spms/sales_person_management_system/doctype/doctor/doctor.py
  spms/sales_person_management_system/doctype/visiting/visiting.py
  spms/sales_person_management_system/report/customer_payment_analysis_v2/customer_payment_analysis_v2.py
Labels: size/L

#65 fix
  spms/sales_person_management_system/report/customer_payment_analysis_v2/customer_payment_analysis_v2.py
Labels: size/L

#66 Revert "fix"
  spms/sales_person_management_system/report/customer_payment_analysis_v2/customer_payment_analysis_v2.py
Labels: size/L

#69 balance calculation
  spms/sales_person_management_system/report/customer_payment_analysis_v2/customer_payment_analysis_v2.py
Labels: size/XS
