Repository E2NEXT/spms, pull requests merged in 2024-03, with the labels that each got.

#36 Change the name of 'Doctor' doctype to 'Client'
  .github/workflows/codesee-arch-diagram.yml
  spms/methods/utils.py
  spms/sales_person_management_system/custom/sales_person.json
  spms/sales_person_management_system/doctype/client/__init__.py
  spms/sales_person_management_system/doctype/client/client.js
  spms/sales_person_management_system/doctype/client/client.json
  spms/sales_person_management_system/doctype/client/client.py
  spms/sales_person_management_system/doctype/client/test_client.py
  spms/sales_person_management_system/doctype/client/test_doctor.py
  spms/sales_person_management_system/doctype/doctor_visit_goal/doctor_visit_goal.json
  spms/sales_person_management_system/doctype/doctor_visited/doctor_visited.json
  spms/sales_person_management_system/doctype/productivity/productivity.json
  spms/sales_person_management_system/doctype/visiting/visiting.js
  spms/sales_person_management_system/doctype/visiting/visiting.json
  spms/sales_person_management_system/workspace/spms/spms.json
Labels: size/XXL

#42 sales person changes
  spms/sales_person_management_system/custom/sales_person.json
  spms/sales_person_management_system/doctype/client/client.js
  spms/sales_person_management_system/doctype/client/client.json
Labels: size/L

#43 new changes to client
  spms/sales_person_management_system/doctype/client/client.js
  spms/sales_person_management_system/doctype/client/client.json
  spms/sales_person_management_system/doctype/client/client.py
Labels: size/S

#44 sales person changes
  spms/sales_person_management_system/custom/sales_person.json
Labels: size/L

#45 Set target
  spms/public/js/sales_person.js
  spms/sales_person_management_system/doctype/client/client.json
  spms/utils/utils.py
Labels: size/XL

#46 export customization for sales person
  spms/sales_person_management_system/custom/sales_person.json
Labels: size/M

#47 New set target
  spms/methods/events/sales_person.py
  spms/public/js/sales_person.js
  spms/sales_person_management_system/custom/sales_person.json
  spms/sales_person_management_system/doctype/productivity/productivity.json
  spms/sales_person_management_system/doctype/visit_goal/visit_goal.js
  spms/sales_person_management_system/doctype/visit_goal/visit_goal.json
  spms/utils/utils.py
Labels: size/L

#48 set target fix
  spms/public/js/sales_person.js
  spms/utils/utils.py
Labels: size/M

#50 New changes 20-21/3
  spms/public/js/sales_person.js
  spms/sales_person_management_system/custom/sales_person.json
  spms/sales_person_management_system/doctype/client/client.js
  spms/sales_person_management_system/doctype/client/client.json
  spms/sales_person_management_system/doctype/client_types/__init__.py
  spms/sales_person_management_system/doctype/client_types/client_types.js
  spms/sales_person_management_system/doctype/client_types/client_types.json
  spms/sales_person_management_system/doctype/client_types/client_types.py
  spms/sales_person_management_system/doctype/client_types/test_client_types.py
  spms/sales_person_management_system/doctype/collecting/collecting.js
  spms/sales_person_management_system/doctype/collecting/collecting.json
  spms/sales_person_management_system/doctype/collecting/collecting.py
  spms/sales_person_management_system/doctype/reference_invoice_collects/reference_invoice_collects.json
  spms/utils/utils.py
Labels: size/XL

#51 24/3 fixes
  spms/public/js/sales_person.js
  spms/sales_person_management_system/doctype/client_types/client_types.json
  spms/sales_person_management_system/doctype/collecting/collecting.json
  spms/sales_person_management_system/doctype/collecting/collecting.py
  spms/utils/utils.py
Labels: size/L

#53 sales person fixes
  spms/methods/utils.py
  spms/public/js/sales_person.js
  spms/sales_person_management_system/custom/sales_person.json
  spms/sales_person_management_system/doctype/collection_target/collection_target.json
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.js
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.json
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.py
  spms/sales_person_management_system/doctype/payment_collection/templates/payment_collection.html
  spms/sales_person_management_system/doctype/payment_collection/templates/payment_collection_row.html
  spms/sales_person_management_system/doctype/productivity/productivity.json
  spms/sales_person_management_system/doctype/sales_target/sales_target.js
  spms/sales_person_management_system/doctype/sales_target/sales_target.json
  spms/sales_person_management_system/doctype/sales_visit/sales_visit.json
  spms/sales_person_management_system/doctype/target_breakdown/target_breakdown.json
  spms/utils/utils.py
Labels: size/L

#54 Reports
  spms/public/js/sales_person.js
  spms/sales_person_management_system/custom/payment_entry.json
  spms/sales_person_management_system/doctype/collection_target/collection_target.js
  spms/sales_person_management_system/doctype/collection_target/collection_target.json
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.js
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.json
  spms/sales_person_management_system/doctype/payment_collection/payment_collection.py
  spms/sales_person_management_system/doctype/sales_target/sales_target.js
  spms/sales_person_management_system/doctype/sales_target/sales_target.py
  spms/sales_person_management_system/doctype/sales_visit/sales_visit.json
  spms/sales_person_management_system/public/js/sales_person.js
  spms/sales_person_management_system/report/salesperson_wise_details/__init__.py
  spms/sales_person_management_system/report/salesperson_wise_details/salesperson_wise_details.js
  spms/sales_person_management_system/report/salesperson_wise_details/salesperson_wise_details.json
  spms/sales_person_management_system/report/salesperson_wise_details/salesperson_wise_details.py
  spms/sales_person_management_system/report/salesperson_wise_targets/__init__.py
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.js
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.json
  spms/sales_person_management_system/report/salesperson_wise_targets/salesperson_wise_targets.py
  spms/sales_person_management_system/workspace/spms/spms.json
  spms/utils/utils.py
Labels: size/XXL
